<a href="https://colab.research.google.com/github/ankile/MIT6.036-Intro-Machine-Learning/blob/master/hw-06/ankile_MIT_6_036_HW06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MIT 6.036 Spring 2020: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.

In [0]:
import numpy as np

# **Problem 2**

You may find it helpful to implement a softmax function to use for solving the problems.

In [0]:
# Implement Softmax
def SM(z):
    '''
    z is a column vector
    '''
    e = np.exp(z)
    return e / np.sum(e)

**Problem 2.A**

In [4]:
z = np.array([[-1, 0, 1]]).T
SM(z)

array([[0.09003057],
       [0.24472847],
       [0.66524096]])

**Problem 2.C - 2.F**

In [14]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T

z = w.T@x
a = SM(z)

# Problem 2.C
a[1].item()

0.6652409557748219

In [15]:
# Problem 2.D
# From 1.1.E: -x*y+x*a_1
dw = -x*y.T+x*a.T
dw

array([[ 0.24472847, -0.33475904,  0.09003057],
       [ 0.24472847, -0.33475904,  0.09003057]])

In [16]:
# Problem 2.E
w2 = w - 0.5 * dw
w2

array([[ 0.87763576, -0.83262048, -2.04501529],
       [-1.12236424,  2.16737952,  0.95498471]])

In [17]:
# Problem 2.F
z2 = w2.T@x
a2 = SM(z2)

a2[1].item()

0.7724528366207931

# **Problem 3**

**Problem 3.1**

You may choose to draft your implementation here. We recommend looking at the ReLU plot at the top of the homework page for better understanding.

In [0]:
def ReLU(z):
    return np.apply_along_axis(func1d=lambda x: np.array([max(0, x.item())]), arr=z, axis=1)

def dReLU_dz(z):
    '''
    z is a column vector
    You should return a column vector
    '''
    return np.apply_along_axis(func1d=lambda x: np.array([1]) if x.item() > 0 else np.array([0]), arr=z, axis=1)

In [0]:
# Problem 3.2 A
W1 = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
W10 = np.array([[-1, -1, -1, -1]]).T
X = np.array([[3, 14]]).T

a1 = ReLU(W1.T@X + W10)
a1.T[0]

array([ 2, 13,  0,  0])

In [0]:
# Problem 3.2 B
W2 = np.array([[1] * 4, [-1] * 4]).T
W20 = np.array([[0, 2]]).T

a2 = SM(W2.T@a1 + W20)
a2.T[0]

array([1.00000000e+00, 6.91440011e-13])

In [0]:
# Problem 3.3 C
x1 = np.array([[0.5, 0.5]]).T
x2 = np.array([[0, 2]]).T
x3 = np.array([[-3, 0.5]]).T

ReLU(W1.T@x1 + W10), ReLU(W1.T@x2 + W10), ReLU(W1.T@x3 + W10)

(array([[0],
        [0],
        [0],
        [0]]), array([[0],
        [1],
        [0],
        [0]]), array([[0],
        [0],
        [2],
        [0]]))

In [0]:
# Problem 3.4 A
SM(np.array([[0, 2]]).T)

array([[0.11920292],
       [0.88079708]])